# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20)),
                ('moduleTitle', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('contentType', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('contentTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=20)),
                ('courseCode', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('isPublished', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('courseCode', models.CharField(max_length=20)),
                ('participant', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20)),
                ('moduleTitle', models.CharField(max_length=200)),
                ('sequenceNumber', models.IntegerField()),
            ],
        ),
    ]
